name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y dkms
      - run: |
          MODULE_NAME=$(awk -F= '/PACKAGE_NAME/ {print $2}' dkms.conf | sed 's/"//g')
          MODULE_VERSION=$(awk -F= '/PACKAGE_VERSION/ {print $2}' dkms.conf | sed 's/"//g')
          dkms mktarball "${MODULE_NAME}/${MODULE_VERSION}" --source-only
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ../*.tar.gz
