name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y dkms debhelper
      - run: dkms mkdeb --source-only
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ../*.deb
